project_name: anylink
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: jonnyan404
  description: Sample project.
  homepage: https://www.mrdoc.fun
  license: MIT
