name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: set up npm
        uses: actions/setup-node@v1
        with:
          node-version: 12
      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: |
          cd server
          go get -v -t -d ./...
      - name: Build ui
        run: |
          cd web
          npm i @vue/cli-service
          npm run build
      - name: Build
        run: |
          cd server
          rm -rf ui
          cp -rf ../web/ui .
          go build -v -o anylink -ldflags "-X main.CommitId=`git rev-parse HEAD`"
          ./anylink tool -v
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
